### ISSUE TITLE
Make use of node-binance-api module

### ISSUE THREAD

**Issue by dioKaratzas** [CkCreative/binance-spot-trading-bot#4]
Why you don't make use of node-binance-api module?

**Comment by CkCreative** [comment]
I didn't know such a module existed, lol. I will take a look

**Comment by dioKaratzas** [comment]
Here is the link ;) https://github.com/jaggedsoft/node-binance-api

**Comment by CkCreative** [comment]
wow! quite comprehensive. I will definately use some of it's features. 🥂
